apiVersion: apps/v1
kind: Deployment
metadata:
    name: llama2-v1-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: llama2-v1
    template:
        metadata:
            labels:
                app: llama2-v1
        spec:
            containers:
                - name: llama2-v1-app
                  image: ghcr.io/multimodal-image
                  args: ['--model-id', 'llama2-v1']
                  ports:
                      - containerPort: 80
            nodeSelector:
                node.kubernetes.io/instance-type: g5.12xlarge

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: llama2-v1-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: llama2-v1-deployment
    minReplicas: 1
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 75

---
apiVersion: v1
kind: Service
metadata:
    name: llama2-v1-service
spec:
    selector:
        app: llama2-v1
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
