apiVersion: apps/v1
kind: Deployment
metadata:
    name: chronos-13b-v2-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            app: chronos-13b-v2
    template:
        metadata:
            labels:
                app: chronos-13b-v2
        spec:
            containers:
                - name: chronos-13b-v2-app
                  image: ghcr.io/huggingface/text-generation-inference:1.0.0
                  args: ['--model-id', 'elinas/chronos-13b-v2', '--quantize', 'gptq']
                  env:
                      - name: GPTQ_BITS
                        value: '4'
                      - name: GPTQ_GROUPSIZE
                        value: '1'
                  ports:
                      - containerPort: 80
            nodeSelector:
                node.kubernetes.io/instance-type: g5.xlarge

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
    name: chronos-13b-v2-hpa
spec:
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: chronos-13b-v2-deployment
    minReplicas: 1
    maxReplicas: 5
    metrics:
        - type: Resource
          resource:
              name: cpu
              target:
                  type: Utilization
                  averageUtilization: 75

---
apiVersion: v1
kind: Service
metadata:
    name: chronos-13b-v2-service
spec:
    selector:
        app: chronos-13b-v2
    ports:
        - protocol: TCP
          port: 8080
          targetPort: 80
